### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by janwerkhoven** [ddavison/sublime-tabs#132]
Hi,

I installed your package, disabled Tabs and Tree View package, restarted Atom, right clicked in any file and started getting the errors below. What do you want me to do?

Kind regards,

Jan

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.205.0
**System**: Mac OS X 10.10.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: /Applications/Atom.app/Contents/Resources/app.asar/src/browser/context-menu.js:1
(function (exports, require, module, __filename, __dirname) { 
                                                              
Unexpected token ILLEGAL
/Applications/Atom.app/Contents/Resources/app.asar/src/browser/context-menu.js:1
(function (exports, require, module, __filename, __dirname) { 
                                                              
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:435:25)
    at Object.Module._extensions..js (module.js:470:10)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/atom-window.js:152:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)

```
At /Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:77

Error: /Applications/Atom.app/Contents/Resources/app.asar/src/browser/context-menu.js:1
(function (exports, require, module, __filename, __dirname) { 
                                                              
Unexpected token ILLEGAL
/Applications/Atom.app/Contents/Resources/app.asar/src/browser/context-menu.js:1
(function (exports, require, module, __filename, __dirname) { 
                                                              
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:435:25)
    at Object.Module._extensions..js (module.js:470:10)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/atom-window.js:152:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
  at metaToValue (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:77:15)
  at BrowserWindow.RemoteMemberFunction [as emit] (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:111:26)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:148:33)
  at HTMLDocument.handler (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
     -3:13.3.0 application:add-project-folder (atom-text-editor.editor.mini.is-focused)
     -2:25.4.0 window:update-available (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-seti-monokai.theme-one-light-ui)
     -2:10.7.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-seti-monokai.theme-one-light-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "seti-monokai"
    ],
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "tabs",
      "tree-view"
    ]
  },
  "editor": {
    "fontSize": 12,
    "invisibles": {},
    "preferredLineLength": 300
  }
}
```

### Installed Packages

```coffee
# User
highlight-selected, v0.10.1
seti-monokai, v0.3.1
sublime-tabs, v0.5.6

# Dev
No dev packages
```

**Comment by ddavison** [comment]
@janwerkhoven thanks so much for opening an issue. I'm not sure if you noticed, but this package is in core now.

take a look at the readme :) no need to install this package anymore

**Comment by janwerkhoven** [comment]
Thanks, yea it's now part of Tabs core package. Thanks mate :)
