### ISSUE TITLE
Failed to load the sublime-tabs package

### ISSUE THREAD

**Issue by Globegitter** [ddavison/sublime-tabs#89]
[Enter steps to reproduce below:]

1. Update to the latest Atom and open any Project (it seems to load in 1.0 API Preview Mode as default)

**Atom Version**: 0.192.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [sublime-tabs](https://github.com/ddavison/sublime-tabs) package, v0.5.3

### Stack Trace

Failed to load the sublime-tabs package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/markus/.atom/packages/sublime-tabs/lib/tabs/tab-view.coffee:4:199)
    at /Users/markus/.atom/packages/sublime-tabs/lib/tabs/tab-view.coffee:13:5
    at Object.<anonymous> (/Users/markus/.atom/packages/sublime-tabs/lib/tabs/tab-view.coffee:170:5)
    at Object.<anonymous> (/Users/markus/.atom/packages/sublime-tabs/lib/tabs/tab-view.coffee:172:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "disabledPackages": [
      "tabs",
      "tree-view",
      "language-sass",
      "linter-eslint",
      "linter"
    ],
    "excludeVcsIgnoredPaths": false
  }
}
```

### Installed Packages

```coffee
# User
Atom-Syntax-highlighting-for-Sass, v0.5.0
auto-indent, v0.1.0
better-handlebars, v0.1.1
color-picker, v1.6.0
editor-stats, v0.17.0
emmet, v2.3.7
es-navigation, v0.1.5
indent-guide-ext, v0.1.0
language-docker, v1.1.3
language-javascript-better, v1.3.0
language-json5, v1.1.0
sublime-tabs, v0.5.3

# Dev
No dev packages
```

**Comment by ddavison** [comment]
Hey @Globegitter thanks for reporting this.  After I updated today, I got all my packages getting the same exact error.  Did any other package you have installed have this issue too?

**Comment by ddavison** [comment]
**EDIT:**  I just Cmd+Q'd, and reran atom after updating ALL my packages, and I'm golden now.. Could you try the same?

**Comment by ddavison** [comment]
Closing this issue, as sublime-tabs is now in [core](https://github.com/atom/tabs/pull/145)
